name: Trigger Airflow DAG on Merge

on:
  push:
    branches:
      - main

jobs:
  trigger-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger DAG via Airflow API
        env:
          AIRFLOW_URL: ${{ secrets.AIRFLOW_URL }}
          AIRFLOW_USER: ${{ secrets.AIRFLOW_USER }}
          AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
        run: |
          python3 -m pip install requests
          python3 -c "
import requests
import datetime
from requests.auth import HTTPBasicAuth

dag_id = 'test_dag'
url = f'{os.environ[\"AIRFLOW_URL\"]}/api/v1/dags/{dag_id}/dagRuns'
auth = HTTPBasicAuth(os.environ['AIRFLOW_USER'], os.environ['AIRFLOW_PASSWORD'])

data = {
  'dag_run_id': f'manual__{datetime.datetime.utcnow().isoformat()}'
}

resp = requests.post(url, json=data, auth=auth)
print('Status:', resp.status_code)
print('Response:', resp.text)
"
